name       : gnome-sharp
version    : 2.24.4
release    : 4
source     :
    - https://github.com/mono/gnome-sharp/archive/2.24.4.tar.gz : 4e72b9b452af9cf54250564b0b633e5a5925f50ddb3b39e97efd0abe69bc077e
license    : LGPL-2.1-only
component  : programming
summary    : Gnome# is a .NET language binding for assorted GNOME libraries
description: |
    Gnome# is a .NET language binding for assorted GNOME libraries.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gtk-sharp-2.0)
    - pkgconfig(libgnomeui-2.0)
    - pkgconfig(monodoc)
    - pkgconfig(popt)
    - pkgconfig(sm)
setup      : |
    %patch -Np1 -i $pkgfiles/02_fix_pkg-config_paths.patch
    %patch -Np1 -i $pkgfiles/04_initialize_dbus_glib_threading.patch
    %patch -Np1 -i $pkgfiles/06_fix_mono_path.patch

    ./bootstrap-${version%.*}
    # re-run configure with our own options
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
