name       : gnome-sharp
version    : 2.24.2
release    : 1
source     :
    - http://ftp.gnome.org/pub/gnome/sources/gnome-sharp/2.24/gnome-sharp-2.24.2.tar.bz2 : 122b1e03966d63ec3389decf5440fb94285907d1b6be48352dcf6aca292cf7b0
license    : LGPL-2.1
summary    : Gnome# is a .NET language binding for assorted GNOME libraries.
description: |
    Gnome# is a .NET language binding for assorted GNOME libraries.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(monodoc)
    - pkgconfig(gtk-sharp-2.0)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
